version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    environment:
      - MARIADB_ROOT_PASSWORD=admin
  backend:
    build: ../server
    env_file: ../server/.env.test
    depends_on:
      - mariadb
  sql-injection:
    build: .
    depends_on:
      - backend
    environment:
      - TEST_URL=http://backend:3000
